### ISSUE TITLE
Team Builder - "default moves" crashes if < 4 moves

### ISSUE THREAD

**Issue by cireficc** [cireficc/pokemon-arena-android#70]
Choosing "Default Moves" in the Team Builder UI will crash if the Pokemon has less than 4 moves. The stack trace:

```
FATAL EXCEPTION: main
    Process: com.pokemonbattlearena.android, PID: 4173
        java.lang.IndexOutOfBoundsException
            at java.util.AbstractList.subList(AbstractList.java:738)
            at com.pokemonbattlearena.android.fragments.team.TeamsHomeFragment$3.onClick(TeamsHomeFragment.java:151)
            at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:163)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by cireficc** [comment]
Closed by #119.
